// Code generated by protoc-gen-go.
// source: current.proto
// DO NOT EDIT!

/*
Package current is a generated protocol buffer package.

It is generated from these files:
	current.proto

It has these top-level messages:
	PostLocationFromBigBrotherRequest
	PostLocationFromBigBrotherReply
	GetLocationRequest
	GetLocationReply
*/
package current

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/zaquestion/current/service/DONOTEDIT/third_party/googleapis/google/api"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PostLocationFromBigBrotherRequest struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Accuracy  float64 `protobuf:"fixed64,3,opt,name=accuracy" json:"accuracy,omitempty"`
	Altitude  float64 `protobuf:"fixed64,4,opt,name=altitude" json:"altitude,omitempty"`
	Bearing   float64 `protobuf:"fixed64,5,opt,name=bearing" json:"bearing,omitempty"`
	Speed     float64 `protobuf:"fixed64,6,opt,name=speed" json:"speed,omitempty"`
}

func (m *PostLocationFromBigBrotherRequest) Reset()         { *m = PostLocationFromBigBrotherRequest{} }
func (m *PostLocationFromBigBrotherRequest) String() string { return proto.CompactTextString(m) }
func (*PostLocationFromBigBrotherRequest) ProtoMessage()    {}
func (*PostLocationFromBigBrotherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

type PostLocationFromBigBrotherReply struct {
	Err string `protobuf:"bytes,2,opt,name=err" json:"err,omitempty"`
}

func (m *PostLocationFromBigBrotherReply) Reset()                    { *m = PostLocationFromBigBrotherReply{} }
func (m *PostLocationFromBigBrotherReply) String() string            { return proto.CompactTextString(m) }
func (*PostLocationFromBigBrotherReply) ProtoMessage()               {}
func (*PostLocationFromBigBrotherReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetLocationRequest struct {
}

func (m *GetLocationRequest) Reset()                    { *m = GetLocationRequest{} }
func (m *GetLocationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLocationRequest) ProtoMessage()               {}
func (*GetLocationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetLocationReply struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Err       string  `protobuf:"bytes,3,opt,name=err" json:"err,omitempty"`
}

func (m *GetLocationReply) Reset()                    { *m = GetLocationReply{} }
func (m *GetLocationReply) String() string            { return proto.CompactTextString(m) }
func (*GetLocationReply) ProtoMessage()               {}
func (*GetLocationReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*PostLocationFromBigBrotherRequest)(nil), "current.PostLocationFromBigBrotherRequest")
	proto.RegisterType((*PostLocationFromBigBrotherReply)(nil), "current.PostLocationFromBigBrotherReply")
	proto.RegisterType((*GetLocationRequest)(nil), "current.GetLocationRequest")
	proto.RegisterType((*GetLocationReply)(nil), "current.GetLocationReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for CurrentService service

type CurrentServiceClient interface {
	PostLocationFromBigBrother(ctx context.Context, in *PostLocationFromBigBrotherRequest, opts ...grpc.CallOption) (*PostLocationFromBigBrotherReply, error)
	GetLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*GetLocationReply, error)
}

type currentServiceClient struct {
	cc *grpc.ClientConn
}

func NewCurrentServiceClient(cc *grpc.ClientConn) CurrentServiceClient {
	return &currentServiceClient{cc}
}

func (c *currentServiceClient) PostLocationFromBigBrother(ctx context.Context, in *PostLocationFromBigBrotherRequest, opts ...grpc.CallOption) (*PostLocationFromBigBrotherReply, error) {
	out := new(PostLocationFromBigBrotherReply)
	err := grpc.Invoke(ctx, "/current.CurrentService/PostLocationFromBigBrother", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currentServiceClient) GetLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*GetLocationReply, error) {
	out := new(GetLocationReply)
	err := grpc.Invoke(ctx, "/current.CurrentService/GetLocation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CurrentService service

type CurrentServiceServer interface {
	PostLocationFromBigBrother(context.Context, *PostLocationFromBigBrotherRequest) (*PostLocationFromBigBrotherReply, error)
	GetLocation(context.Context, *GetLocationRequest) (*GetLocationReply, error)
}

func RegisterCurrentServiceServer(s *grpc.Server, srv CurrentServiceServer) {
	s.RegisterService(&_CurrentService_serviceDesc, srv)
}

func _CurrentService_PostLocationFromBigBrother_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostLocationFromBigBrotherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentServiceServer).PostLocationFromBigBrother(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/current.CurrentService/PostLocationFromBigBrother",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentServiceServer).PostLocationFromBigBrother(ctx, req.(*PostLocationFromBigBrotherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CurrentService_GetLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentServiceServer).GetLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/current.CurrentService/GetLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentServiceServer).GetLocation(ctx, req.(*GetLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CurrentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "current.CurrentService",
	HandlerType: (*CurrentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostLocationFromBigBrother",
			Handler:    _CurrentService_PostLocationFromBigBrother_Handler,
		},
		{
			MethodName: "GetLocation",
			Handler:    _CurrentService_GetLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("current.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x52, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x25, 0xed, 0xd7, 0xf6, 0xeb, 0x2d, 0x4a, 0xbd, 0x14, 0x89, 0xb1, 0xa0, 0x66, 0x55, 0x5c,
	0x34, 0x60, 0xdf, 0xa0, 0x82, 0x6e, 0x5c, 0x48, 0xdd, 0xb8, 0x12, 0x26, 0xe9, 0x25, 0x0e, 0x8c,
	0x33, 0x71, 0x32, 0x11, 0xba, 0xf5, 0x09, 0x04, 0x9f, 0xc9, 0x27, 0xf0, 0x15, 0x7c, 0x0d, 0x41,
	0x32, 0x99, 0x44, 0xc5, 0x5f, 0xdc, 0xe5, 0x9c, 0x73, 0xcf, 0x9c, 0xfb, 0x13, 0x58, 0x4b, 0x0a,
	0xad, 0x49, 0x9a, 0x69, 0xa6, 0x95, 0x51, 0xd8, 0x73, 0x30, 0x18, 0xa7, 0x4a, 0xa5, 0x82, 0x22,
	0x96, 0xf1, 0x88, 0x49, 0xa9, 0x0c, 0x33, 0x5c, 0xc9, 0xbc, 0x2a, 0x0b, 0x1f, 0x3c, 0xd8, 0x3b,
	0x55, 0xb9, 0x39, 0x51, 0x89, 0xe5, 0x8f, 0xb4, 0xba, 0x9a, 0xf3, 0x74, 0xae, 0x95, 0xb9, 0x24,
	0xbd, 0xa0, 0xeb, 0x82, 0x72, 0x83, 0x01, 0xfc, 0x17, 0xcc, 0x70, 0x53, 0x2c, 0xc9, 0xf7, 0x76,
	0xbd, 0x89, 0xb7, 0x68, 0x30, 0x8e, 0xa1, 0x2f, 0x94, 0x4c, 0x2b, 0xb1, 0x65, 0xc5, 0x57, 0xa2,
	0x74, 0xb2, 0x24, 0x29, 0x34, 0x4b, 0x56, 0x7e, 0xbb, 0x72, 0xd6, 0xd8, 0x6a, 0xc2, 0xbd, 0xfa,
	0xcf, 0x69, 0x0e, 0xa3, 0x0f, 0xbd, 0x98, 0x98, 0xe6, 0x32, 0xf5, 0x3b, 0x56, 0xaa, 0x21, 0x8e,
	0xa0, 0x93, 0x67, 0x44, 0x4b, 0xbf, 0x6b, 0xf9, 0x0a, 0x84, 0x33, 0xd8, 0xf9, 0x6e, 0x8c, 0x4c,
	0xac, 0x70, 0x08, 0x6d, 0xd2, 0xda, 0xb6, 0xd8, 0x5f, 0x94, 0x9f, 0xe1, 0x08, 0xf0, 0x98, 0x1a,
	0x8f, 0x1b, 0x36, 0xbc, 0x80, 0xe1, 0x3b, 0xb6, 0xf4, 0xfe, 0x7d, 0x01, 0x2e, 0xb5, 0xdd, 0xa4,
	0x1e, 0x3c, 0x7b, 0xb0, 0x7e, 0x58, 0x1d, 0xe7, 0x8c, 0xf4, 0x0d, 0x4f, 0x08, 0xef, 0x3c, 0x08,
	0xbe, 0x6e, 0x1f, 0xf7, 0xa7, 0xf5, 0x6d, 0x7f, 0x3c, 0x55, 0x30, 0xf9, 0x55, 0x6d, 0x26, 0x56,
	0xe1, 0xf8, 0xf6, 0xf1, 0xe9, 0xbe, 0xb5, 0x89, 0xa3, 0x48, 0xb8, 0xaa, 0x28, 0xe6, 0x69, 0xec,
	0x32, 0xcf, 0x61, 0xf0, 0x66, 0x0b, 0xb8, 0xdd, 0x3c, 0xfb, 0x71, 0x63, 0xc1, 0xd6, 0xe7, 0x62,
	0x19, 0xb2, 0x61, 0x43, 0x06, 0xd8, 0x6f, 0x42, 0xe2, 0xae, 0xfd, 0xf3, 0x66, 0x2f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xe4, 0x7c, 0xf5, 0xba, 0xb1, 0x02, 0x00, 0x00,
}
