// Code generated by truss.
// Rerunning truss will overwrite this file.
// DO NOT EDIT!
// Version: a41ee29fb6
// Version Date: Fri May 26 18:19:22 UTC 2017

package svc

// This file contains methods to make individual endpoints from services,
// request and response types to serve those endpoints, as well as encoders and
// decoders for those types, for all of our supported transport serialization
// formats. It also includes endpoint middlewares.

import (
	"fmt"
	"golang.org/x/net/context"

	"github.com/go-kit/kit/endpoint"

	pb "github.com/zaquestion/current/current-service"
)

// Endpoints collects all of the endpoints that compose an add service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
//
// In a server, it's useful for functions that need to operate on a per-endpoint
// basis. For example, you might pass an Endpoints to a function that produces
// an http.Handler, with each method (endpoint) wired up to a specific path. (It
// is probably a mistake in design to invoke the Service methods on the
// Endpoints struct in a server.)
//
// In a client, it's useful to collect individually constructed endpoints into a
// single type that implements the Service interface. For example, you might
// construct individual endpoints using transport/http.NewClient, combine them into an Endpoints, and return it to the caller as a Service.
type Endpoints struct {
	PostLocationBigBrotherEndpoint endpoint.Endpoint
	PostLocationTaskerEndpoint     endpoint.Endpoint
	GetLocationEndpoint            endpoint.Endpoint
}

// Endpoints

func (e Endpoints) PostLocationBigBrother(ctx context.Context, in *pb.PostLocationBigBrotherRequest) (*pb.Error, error) {
	response, err := e.PostLocationBigBrotherEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.Error), nil
}

func (e Endpoints) PostLocationTasker(ctx context.Context, in *pb.PostLocationTaskerRequest) (*pb.Error, error) {
	response, err := e.PostLocationTaskerEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.Error), nil
}

func (e Endpoints) GetLocation(ctx context.Context, in *pb.GetLocationRequest) (*pb.Location, error) {
	response, err := e.GetLocationEndpoint(ctx, in)
	if err != nil {
		return nil, err
	}
	return response.(*pb.Location), nil
}

// Make Endpoints

func MakePostLocationBigBrotherEndpoint(s pb.CurrentServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.PostLocationBigBrotherRequest)
		v, err := s.PostLocationBigBrother(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakePostLocationTaskerEndpoint(s pb.CurrentServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.PostLocationTaskerRequest)
		v, err := s.PostLocationTasker(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

func MakeGetLocationEndpoint(s pb.CurrentServer) endpoint.Endpoint {
	return func(ctx context.Context, request interface{}) (response interface{}, err error) {
		req := request.(*pb.GetLocationRequest)
		v, err := s.GetLocation(ctx, req)
		if err != nil {
			return nil, err
		}
		return v, nil
	}
}

// WrapAllExcept wraps each Endpoint field of struct Endpoints with a
// go-kit/kit/endpoint.Middleware.
// Use this for applying a set of middlewares to every endpoint in the service.
// Optionally, endpoints can be passed in by name to be excluded from being wrapped.
// WrapAllExcept(middleware, "Status", "Ping")
func (e *Endpoints) WrapAllExcept(middleware endpoint.Middleware, excluded ...string) {
	included := map[string]struct{}{
		"PostLocationBigBrother": struct{}{},
		"PostLocationTasker":     struct{}{},
		"GetLocation":            struct{}{},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc, _ := range included {
		if inc == "PostLocationBigBrother" {
			e.PostLocationBigBrotherEndpoint = middleware(e.PostLocationBigBrotherEndpoint)
		}
		if inc == "PostLocationTasker" {
			e.PostLocationTaskerEndpoint = middleware(e.PostLocationTaskerEndpoint)
		}
		if inc == "GetLocation" {
			e.GetLocationEndpoint = middleware(e.GetLocationEndpoint)
		}
	}
}

// LabeledMiddleware will get passed the handler name when passed to
// WrapAllLabeledExcept, this can be used to write a generic metrics
// middleware which can send the handler name to the metrics collector.
type LabeledMiddleware func(string, endpoint.Endpoint) endpoint.Endpoint

// WrapAllLabeledExcept wraps each Endpoint field of struct Endpoints with a
// LabeledMiddleware, which will receive the name of the handler. See
// LabeldMiddleware. See method WrapAllExept for details on excluded
// functionality.
func (e *Endpoints) WrapAllLabeledExcept(middleware LabeledMiddleware, excluded ...string) {
	included := map[string]struct{}{
		"PostLocationBigBrother": struct{}{},
		"PostLocationTasker":     struct{}{},
		"GetLocation":            struct{}{},
	}

	for _, ex := range excluded {
		if _, ok := included[ex]; !ok {
			panic(fmt.Sprintf("Excluded endpoint '%s' does not exist; see middlewares/endpoints.go", ex))
		}
		delete(included, ex)
	}

	for inc, _ := range included {
		if inc == "PostLocationBigBrother" {
			e.PostLocationBigBrotherEndpoint = middleware("PostLocationBigBrother", e.PostLocationBigBrotherEndpoint)
		}
		if inc == "PostLocationTasker" {
			e.PostLocationTaskerEndpoint = middleware("PostLocationTasker", e.PostLocationTaskerEndpoint)
		}
		if inc == "GetLocation" {
			e.GetLocationEndpoint = middleware("GetLocation", e.GetLocationEndpoint)
		}
	}
}
