// Code generated by protoc-gen-go. DO NOT EDIT.
// source: current.proto

/*
Package current is a generated protocol buffer package.

It is generated from these files:
	current.proto

It has these top-level messages:
	PostLocationBigBrotherRequest
	PostLocationTaskerRequest
	Empty
	GetLocationRequest
	Location
*/
package current

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/TuneLab/truss/deftree/googlethirdparty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PostLocationBigBrotherRequest struct {
	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Accuracy  float64 `protobuf:"fixed64,3,opt,name=accuracy" json:"accuracy,omitempty"`
	Altitude  float64 `protobuf:"fixed64,4,opt,name=altitude" json:"altitude,omitempty"`
	Bearing   float64 `protobuf:"fixed64,5,opt,name=bearing" json:"bearing,omitempty"`
	Speed     float64 `protobuf:"fixed64,6,opt,name=speed" json:"speed,omitempty"`
	Battlevel int32   `protobuf:"varint,7,opt,name=battlevel" json:"battlevel,omitempty"`
	Time      string  `protobuf:"bytes,8,opt,name=time" json:"time,omitempty"`
}

func (m *PostLocationBigBrotherRequest) Reset()                    { *m = PostLocationBigBrotherRequest{} }
func (m *PostLocationBigBrotherRequest) String() string            { return proto.CompactTextString(m) }
func (*PostLocationBigBrotherRequest) ProtoMessage()               {}
func (*PostLocationBigBrotherRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PostLocationBigBrotherRequest) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PostLocationBigBrotherRequest) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *PostLocationBigBrotherRequest) GetAccuracy() float64 {
	if m != nil {
		return m.Accuracy
	}
	return 0
}

func (m *PostLocationBigBrotherRequest) GetAltitude() float64 {
	if m != nil {
		return m.Altitude
	}
	return 0
}

func (m *PostLocationBigBrotherRequest) GetBearing() float64 {
	if m != nil {
		return m.Bearing
	}
	return 0
}

func (m *PostLocationBigBrotherRequest) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *PostLocationBigBrotherRequest) GetBattlevel() int32 {
	if m != nil {
		return m.Battlevel
	}
	return 0
}

func (m *PostLocationBigBrotherRequest) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type PostLocationTaskerRequest struct {
	Location []float64 `protobuf:"fixed64,1,rep,packed,name=location" json:"location,omitempty"`
	Speed    float64   `protobuf:"fixed64,2,opt,name=speed" json:"speed,omitempty"`
	Battery  int32     `protobuf:"varint,3,opt,name=battery" json:"battery,omitempty"`
	Charging bool      `protobuf:"varint,4,opt,name=charging" json:"charging,omitempty"`
	DateTime string    `protobuf:"bytes,5,opt,name=date_time,json=dateTime" json:"date_time,omitempty"`
	Secret   string    `protobuf:"bytes,6,opt,name=secret" json:"secret,omitempty"`
}

func (m *PostLocationTaskerRequest) Reset()                    { *m = PostLocationTaskerRequest{} }
func (m *PostLocationTaskerRequest) String() string            { return proto.CompactTextString(m) }
func (*PostLocationTaskerRequest) ProtoMessage()               {}
func (*PostLocationTaskerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PostLocationTaskerRequest) GetLocation() []float64 {
	if m != nil {
		return m.Location
	}
	return nil
}

func (m *PostLocationTaskerRequest) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *PostLocationTaskerRequest) GetBattery() int32 {
	if m != nil {
		return m.Battery
	}
	return 0
}

func (m *PostLocationTaskerRequest) GetCharging() bool {
	if m != nil {
		return m.Charging
	}
	return false
}

func (m *PostLocationTaskerRequest) GetDateTime() string {
	if m != nil {
		return m.DateTime
	}
	return ""
}

func (m *PostLocationTaskerRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type GetLocationRequest struct {
	Secret string `protobuf:"bytes,1,opt,name=secret" json:"secret,omitempty"`
}

func (m *GetLocationRequest) Reset()                    { *m = GetLocationRequest{} }
func (m *GetLocationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetLocationRequest) ProtoMessage()               {}
func (*GetLocationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetLocationRequest) GetSecret() string {
	if m != nil {
		return m.Secret
	}
	return ""
}

type Location struct {
	Latitude    float64 `protobuf:"fixed64,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude   float64 `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Speed       float64 `protobuf:"fixed64,3,opt,name=speed" json:"speed,omitempty"`
	Battery     int32   `protobuf:"varint,4,opt,name=battery" json:"battery,omitempty"`
	Charging    bool    `protobuf:"varint,5,opt,name=charging" json:"charging,omitempty"`
	LastUpdated string  `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated" json:"last_updated,omitempty"`
}

func (m *Location) Reset()                    { *m = Location{} }
func (m *Location) String() string            { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()               {}
func (*Location) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Location) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Location) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Location) GetSpeed() float64 {
	if m != nil {
		return m.Speed
	}
	return 0
}

func (m *Location) GetBattery() int32 {
	if m != nil {
		return m.Battery
	}
	return 0
}

func (m *Location) GetCharging() bool {
	if m != nil {
		return m.Charging
	}
	return false
}

func (m *Location) GetLastUpdated() string {
	if m != nil {
		return m.LastUpdated
	}
	return ""
}

func init() {
	proto.RegisterType((*PostLocationBigBrotherRequest)(nil), "current.PostLocationBigBrotherRequest")
	proto.RegisterType((*PostLocationTaskerRequest)(nil), "current.PostLocationTaskerRequest")
	proto.RegisterType((*Empty)(nil), "current.Empty")
	proto.RegisterType((*GetLocationRequest)(nil), "current.GetLocationRequest")
	proto.RegisterType((*Location)(nil), "current.Location")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Current service

type CurrentClient interface {
	PostLocationBigBrother(ctx context.Context, in *PostLocationBigBrotherRequest, opts ...grpc.CallOption) (*Empty, error)
	PostLocationTasker(ctx context.Context, in *PostLocationTaskerRequest, opts ...grpc.CallOption) (*Empty, error)
	GetLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*Location, error)
}

type currentClient struct {
	cc *grpc.ClientConn
}

func NewCurrentClient(cc *grpc.ClientConn) CurrentClient {
	return &currentClient{cc}
}

func (c *currentClient) PostLocationBigBrother(ctx context.Context, in *PostLocationBigBrotherRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/current.Current/PostLocationBigBrother", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currentClient) PostLocationTasker(ctx context.Context, in *PostLocationTaskerRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/current.Current/PostLocationTasker", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *currentClient) GetLocation(ctx context.Context, in *GetLocationRequest, opts ...grpc.CallOption) (*Location, error) {
	out := new(Location)
	err := grpc.Invoke(ctx, "/current.Current/GetLocation", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Current service

type CurrentServer interface {
	PostLocationBigBrother(context.Context, *PostLocationBigBrotherRequest) (*Empty, error)
	PostLocationTasker(context.Context, *PostLocationTaskerRequest) (*Empty, error)
	GetLocation(context.Context, *GetLocationRequest) (*Location, error)
}

func RegisterCurrentServer(s *grpc.Server, srv CurrentServer) {
	s.RegisterService(&_Current_serviceDesc, srv)
}

func _Current_PostLocationBigBrother_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostLocationBigBrotherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentServer).PostLocationBigBrother(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/current.Current/PostLocationBigBrother",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentServer).PostLocationBigBrother(ctx, req.(*PostLocationBigBrotherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Current_PostLocationTasker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostLocationTaskerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentServer).PostLocationTasker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/current.Current/PostLocationTasker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentServer).PostLocationTasker(ctx, req.(*PostLocationTaskerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Current_GetLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CurrentServer).GetLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/current.Current/GetLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CurrentServer).GetLocation(ctx, req.(*GetLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Current_serviceDesc = grpc.ServiceDesc{
	ServiceName: "current.Current",
	HandlerType: (*CurrentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostLocationBigBrother",
			Handler:    _Current_PostLocationBigBrother_Handler,
		},
		{
			MethodName: "PostLocationTasker",
			Handler:    _Current_PostLocationTasker_Handler,
		},
		{
			MethodName: "GetLocation",
			Handler:    _Current_GetLocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "current.proto",
}

func init() { proto.RegisterFile("current.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 500 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4b, 0x8e, 0xd3, 0x40,
	0x10, 0x86, 0xd5, 0x49, 0x1c, 0xdb, 0x15, 0x40, 0x4c, 0x6b, 0x88, 0x4c, 0x32, 0x48, 0xc1, 0x0b,
	0x14, 0x21, 0x14, 0x4b, 0xb0, 0x63, 0x39, 0x23, 0xc4, 0x66, 0x16, 0x23, 0x2b, 0xac, 0x47, 0x6d,
	0xbb, 0x70, 0x2c, 0x1c, 0xb7, 0x69, 0x97, 0x91, 0xb2, 0xe5, 0x0a, 0xdc, 0x04, 0x36, 0xdc, 0x83,
	0x2b, 0x70, 0x03, 0x2e, 0x80, 0xdc, 0x7e, 0x25, 0x64, 0xc2, 0x66, 0x76, 0xf9, 0xeb, 0x77, 0x3d,
	0xbe, 0x54, 0x35, 0x3c, 0x0c, 0x4b, 0xa5, 0x30, 0xa3, 0x55, 0xae, 0x24, 0x49, 0x6e, 0x36, 0x72,
	0x76, 0x15, 0x27, 0xb4, 0x29, 0x83, 0x55, 0x28, 0xb7, 0xde, 0xba, 0xcc, 0xf0, 0x5a, 0x04, 0x1e,
	0xa9, 0xb2, 0x28, 0xbc, 0x08, 0x3f, 0x92, 0x42, 0xf4, 0x62, 0x29, 0xe3, 0x14, 0x69, 0x93, 0xa8,
	0x28, 0x17, 0x8a, 0x76, 0x9e, 0xc8, 0x32, 0x49, 0x82, 0x12, 0x99, 0x15, 0x75, 0x35, 0xf7, 0x0f,
	0x83, 0x67, 0x37, 0xb2, 0xa0, 0x6b, 0x19, 0xea, 0xf8, 0x65, 0x12, 0x5f, 0x2a, 0x49, 0x1b, 0x54,
	0x3e, 0x7e, 0x2e, 0xb1, 0x20, 0x3e, 0x03, 0x2b, 0x15, 0x94, 0x50, 0x19, 0xa1, 0xc3, 0x16, 0x6c,
	0xc9, 0xfc, 0x4e, 0xf3, 0x0b, 0xb0, 0x53, 0x99, 0xc5, 0xb5, 0x39, 0xd0, 0x66, 0x1f, 0xa8, 0x32,
	0x45, 0x18, 0x96, 0x4a, 0x84, 0x3b, 0x67, 0x58, 0x67, 0xb6, 0x5a, 0x7b, 0x69, 0x53, 0x75, 0xd4,
	0x78, 0x8d, 0xe6, 0x0e, 0x98, 0x01, 0x0a, 0x95, 0x64, 0xb1, 0x63, 0x68, 0xab, 0x95, 0xfc, 0x1c,
	0x8c, 0x22, 0x47, 0x8c, 0x9c, 0xb1, 0x8e, 0xd7, 0xa2, 0x9a, 0x22, 0x10, 0x44, 0x29, 0x7e, 0xc1,
	0xd4, 0x31, 0x17, 0x6c, 0x69, 0xf8, 0x7d, 0x80, 0x73, 0x18, 0x51, 0xb2, 0x45, 0xc7, 0x5a, 0xb0,
	0xa5, 0xed, 0xeb, 0xdf, 0xee, 0x4f, 0x06, 0x4f, 0xf7, 0xa9, 0xd7, 0xa2, 0xf8, 0x74, 0x48, 0xdc,
	0x18, 0x0e, 0x5b, 0x0c, 0x35, 0x71, 0xa3, 0xfb, 0x09, 0x06, 0xfb, 0x13, 0x54, 0x13, 0x0b, 0x22,
	0x54, 0x35, 0xa8, 0xe1, 0xb7, 0xb2, 0xaa, 0x15, 0x6e, 0x84, 0x8a, 0x2b, 0x98, 0x8a, 0xd3, 0xf2,
	0x3b, 0xcd, 0xe7, 0x60, 0x47, 0x82, 0xf0, 0x56, 0x8f, 0x67, 0xe8, 0xf1, 0xac, 0x2a, 0xb0, 0x4e,
	0xb6, 0xc8, 0xa7, 0x30, 0x2e, 0x30, 0x54, 0x48, 0x9a, 0xd5, 0xf6, 0x1b, 0xe5, 0x9a, 0x60, 0xbc,
	0xdb, 0xe6, 0xb4, 0x73, 0x5f, 0x01, 0x7f, 0x8f, 0x1d, 0x41, 0x3b, 0x7b, 0x9f, 0xc6, 0x0e, 0xd2,
	0x7e, 0x30, 0xb0, 0xda, 0x6f, 0xef, 0xb1, 0xd2, 0x0e, 0x7f, 0x78, 0x02, 0x7f, 0x74, 0x1a, 0xdf,
	0xf8, 0x07, 0xff, 0x39, 0x3c, 0x48, 0x45, 0x41, 0xb7, 0x65, 0x5e, 0x41, 0x47, 0x0d, 0xe7, 0xa4,
	0x8a, 0x7d, 0xa8, 0x43, 0xaf, 0xbf, 0x0f, 0xc0, 0xbc, 0xaa, 0xcf, 0x9d, 0x67, 0x30, 0xbd, 0xfb,
	0x50, 0xf9, 0x8b, 0x55, 0xfb, 0x42, 0xfe, 0x7b, 0xc9, 0xb3, 0x47, 0xdd, 0x77, 0xf5, 0x3f, 0x78,
	0xf1, 0xf5, 0xd7, 0xef, 0x6f, 0x83, 0xa9, 0x7b, 0xee, 0xb5, 0xeb, 0xf5, 0x82, 0x24, 0x0e, 0x9a,
	0xaa, 0x08, 0xfc, 0xf8, 0x44, 0xb8, 0x7b, 0x67, 0xaf, 0x83, 0xfb, 0x39, 0xea, 0x33, 0xd7, 0x7d,
	0x9e, 0xb8, 0x8f, 0xfb, 0x3e, 0xa4, 0x13, 0xde, 0xb2, 0x97, 0xfc, 0x06, 0x26, 0x7b, 0x6b, 0xe4,
	0xf3, 0x2e, 0xf7, 0x78, 0xb9, 0xb3, 0xb3, 0xce, 0x6c, 0x1d, 0xf7, 0x4c, 0xd7, 0x9e, 0x70, 0xbb,
	0xab, 0x1d, 0x8c, 0xf5, 0xcb, 0x7e, 0xf3, 0x37, 0x00, 0x00, 0xff, 0xff, 0xad, 0x0a, 0xc2, 0x10,
	0x38, 0x04, 0x00, 0x00,
}
