// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: d5b3153b9f
// Version Date: Thu Jul 27 18:20:46 UTC 2017

package handlers

import (
	pb "github.com/zaquestion/current/current-service"
)

// PostLocationBigBrother implements Service.
func PostLocationBigBrother(LatitudePostLocationBigBrother float64, LongitudePostLocationBigBrother float64, AccuracyPostLocationBigBrother float64, AltitudePostLocationBigBrother float64, BearingPostLocationBigBrother float64, SpeedPostLocationBigBrother float64, BattlevelPostLocationBigBrother int32, TimePostLocationBigBrother string) (*pb.PostLocationBigBrotherRequest, error) {
	request := pb.PostLocationBigBrotherRequest{
		Latitude:  LatitudePostLocationBigBrother,
		Longitude: LongitudePostLocationBigBrother,
		Accuracy:  AccuracyPostLocationBigBrother,
		Altitude:  AltitudePostLocationBigBrother,
		Bearing:   BearingPostLocationBigBrother,
		Speed:     SpeedPostLocationBigBrother,
		Battlevel: BattlevelPostLocationBigBrother,
		Time:      TimePostLocationBigBrother,
	}
	return &request, nil
}

// PostLocationTasker implements Service.
func PostLocationTasker(LocationPostLocationTasker []float64, SpeedPostLocationTasker float64, BatteryPostLocationTasker int32, ChargingPostLocationTasker bool, DateTimePostLocationTasker string, SecretPostLocationTasker string) (*pb.PostLocationTaskerRequest, error) {
	request := pb.PostLocationTaskerRequest{
		Location: LocationPostLocationTasker,
		Speed:    SpeedPostLocationTasker,
		Battery:  BatteryPostLocationTasker,
		Charging: ChargingPostLocationTasker,
		DateTime: DateTimePostLocationTasker,
		Secret:   SecretPostLocationTasker,
	}
	return &request, nil
}

// GetLocation implements Service.
func GetLocation(SecretGetLocation string) (*pb.GetLocationRequest, error) {
	request := pb.GetLocationRequest{
		Secret: SecretGetLocation,
	}
	return &request, nil
}
