// Code generated by truss.
// Rerunning truss will overwrite this file.
// DO NOT EDIT!
// Version: a41ee29fb6
// Version Date: Fri May 26 18:19:22 UTC 2017

package handlers

import (
	pb "github.com/zaquestion/current/current-service"
)

// PostLocationBigBrother implements Service.
func PostLocationBigBrother(LatitudePostLocationBigBrother float64, LongitudePostLocationBigBrother float64, AccuracyPostLocationBigBrother float64, AltitudePostLocationBigBrother float64, BearingPostLocationBigBrother float64, SpeedPostLocationBigBrother float64, BattlevelPostLocationBigBrother int32, TimePostLocationBigBrother string) (*pb.PostLocationBigBrotherRequest, error) {
	request := pb.PostLocationBigBrotherRequest{
		Latitude:  LatitudePostLocationBigBrother,
		Longitude: LongitudePostLocationBigBrother,
		Accuracy:  AccuracyPostLocationBigBrother,
		Altitude:  AltitudePostLocationBigBrother,
		Bearing:   BearingPostLocationBigBrother,
		Speed:     SpeedPostLocationBigBrother,
		Battlevel: BattlevelPostLocationBigBrother,
		Time:      TimePostLocationBigBrother,
	}
	return &request, nil
}

// PostLocationTasker implements Service.
func PostLocationTasker(LocationPostLocationTasker []float64, BatteryPostLocationTasker int32, TimePostLocationTasker string) (*pb.PostLocationTaskerRequest, error) {
	request := pb.PostLocationTaskerRequest{
		Location: LocationPostLocationTasker,
		Battery:  BatteryPostLocationTasker,
		Time:     TimePostLocationTasker,
	}
	return &request, nil
}

// GetLocation implements Service.
func GetLocation() (*pb.GetLocationRequest, error) {
	request := pb.GetLocationRequest{}
	return &request, nil
}
